### ISSUE TITLE
Issue on mobile devices

### ISSUE THREAD

**Issue by Eldenroot** [martec/Rin-Editor#20] opened 2017-10-25 12:49 UTC
https://community.mybb.com/thread-189422-post-1287260.html#pid1287260

and 

https://community.mybb.com/thread-189422-post-1287287.html#pid1287287

I am not the only one :(

**Comment by WildcardSearch** [comment] 2017-10-25 20:57
This is a duplicate of #17 (although this issue is title more appropriately)

**Comment by martec** [comment] 2017-10-28 02:10
duplicated and closed.

**Comment by martec** [comment] 2019-01-03 08:33
i cant't reproduce this issue using chrome of android 9 in my test forum https://community.mybb.com/thread-189422-post-1321521.html#pid1321521 . i tried in source and wysiwyg mode.
Closed for now. Create another issue if issue persist.

**Closed by martec** 2019-01-03 08:33 UTC
